//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLBGatewayConfiguration) DeepCopyInto(out *NLBGatewayConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBGatewayConfiguration.
func (in *NLBGatewayConfiguration) DeepCopy() *NLBGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(NLBGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLBGatewayConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLBGatewayConfigurationList) DeepCopyInto(out *NLBGatewayConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NLBGatewayConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBGatewayConfigurationList.
func (in *NLBGatewayConfigurationList) DeepCopy() *NLBGatewayConfigurationList {
	if in == nil {
		return nil
	}
	out := new(NLBGatewayConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NLBGatewayConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLBGatewayConfigurationSpec) DeepCopyInto(out *NLBGatewayConfigurationSpec) {
	*out = *in
	if in.LoadBalancerScheme != nil {
		in, out := &in.LoadBalancerScheme, &out.LoadBalancerScheme
		*out = new(LBScheme)
		**out = **in
	}
	if in.LoadBalancerSubnets != nil {
		in, out := &in.LoadBalancerSubnets, &out.LoadBalancerSubnets
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBGatewayConfigurationSpec.
func (in *NLBGatewayConfigurationSpec) DeepCopy() *NLBGatewayConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(NLBGatewayConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NLBGatewayConfigurationStatus) DeepCopyInto(out *NLBGatewayConfigurationStatus) {
	*out = *in
	if in.ObservedGatewayConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayConfigurationGeneration, &out.ObservedGatewayConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ObservedGatewayClassConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayClassConfigurationGeneration, &out.ObservedGatewayClassConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NLBGatewayConfigurationStatus.
func (in *NLBGatewayConfigurationStatus) DeepCopy() *NLBGatewayConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(NLBGatewayConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
